### ISSUE TITLE
Extension breaks R#'s (9.2) Quickfix functionality

### ISSUE THREAD

**Issue by breki** [SergeyTeplyakov/ReSharperContractExtensions#57]
After installing the extension, Resharper no longer displays the Quickfix icon (a hammer) left of the code line, and also the Alt+Enter keyboard shortcut no longer works. So not only Code Contract context actions are unavailable, but also R#'s standard ones (like "Introduce and initialize field..." etc).

I've tested it on both VS 2012 and 2013. After deinstalling the extension, the Quickfix is back and working.

**Comment by tom-englert** [comment]
I encountered this with 2015 only - but not always. 
Sometimes it works, and sometimes not, I did not find a pattern, yet...

**Comment by georgiosd** [comment]
+1

**Comment by epirion** [comment]
I have the same issue (in R# 9.2 in VS2012), can we set this issue to showstopper?

**Comment by Diagonactic** [comment]
Hi everyone, I'm getting the same issue here.

Looks like this is caused by an exception being thrown about a method not being implemented. I'm guessing it's an incompatibility between the API this targeted and the 9.2 API.  

I cloned the repo and am most of the way through updating the references/interface implementations to work with the new API. Once I'm done I'll give it a test and if the problem goes away I'll fork and submit a pull request.

**Comment by SergeyTeplyakov** [comment]
@Diagonactic That would be awesome!

Sorry for late replies and lack of activity in this repo:(

**Comment by georgiosd** [comment]
No worries @SergeyTeplyakov, we all live on non-open source projects :)
@Diagonactic thanks for taking a look

**Comment by Diagonactic** [comment]
@SergeyTeplyakov The API changes so frequently, this is sort of par for the course with ReSharper extensions, it appears :)

I was hoping to have better news than I have today. I've done a few of these over the past months but never one that was quite like this.

The "work in progress" is at https://github.com/Diagonactic/ReSharperContractExtensions

It's *far* from ready.  I got as far as making the package build and getting the nuget package to show up in the extension manager when pointed at a local repository containing it.  The classes implementing IHighlighting were updated, using statements were modified and obsolete items were removed. This only applies (hopefully) to the "R82" project.  The nuget package for the new API was added (along with a million references, most of which probably need to be removed).

Despite showing up, something is definitely wrong. Nothing of the extension appears in Visual Studio after its installed, not even the settings page. On the plus side, it no longer keeps the lightbulb from showing (yeah, guessing that's because it's effectively "not installed" as far as ReSharper is concerned :) ...) 
I didn't have time yesterday to troubleshoot and I probably won't have much time this week (day job, so it's evening play-time work) until the weekend.

Still to do:
(Probably) add these changes in as a new project specific to 9.2 - I updated the 8.2 version and that likely means that 8.2 version will no longer be supported as a result.
Make the test projects build/work.
Make the actual extension work.
Fix anything I've done wrong in my changes ;)

I'll update my forked repo and this thread if I make any progress.  I'm not terribly studied up on ReSharper extension development - I've converted a few to work with 9.2 and "gotten lucky" in that it was often pretty straight forward, but as far as this one is concerned, I'll have to do some research to figure out where to begin troubleshooting.  In the meantime, if anyone reading has any suggestions, reply away.

Take care everyone!

**Comment by breki** [comment]
Great effort, @Diagonactic!
About the R# 9.2 changes: perhaps contacting JetBrains guys would help? They are quite responsive (at least from my experience with their Twitter account: https://twitter.com/resharper).

**Comment by SergeyTeplyakov** [comment]
@Diagonactic THanks a lot for your help with this release.

I've published new version: https://github.com/SergeyTeplyakov/ReSharperContractExtensions/releases/tag/0.9.2.5

**Comment by breki** [comment]
Thanks, guys!

**Comment by Diagonactic** [comment]
Sweet!! Thanks @SergeyTeplyakov.  Will be updating today.

**Comment by georgiosd** [comment]
Kudos!
